services:
  db:
    image: postgres:16-alpine
    container_name: mobile-banking-postgres
    environment:
      - POSTGRES_DB=mobile_banking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mobile-banking-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobile-banking-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mobile_banking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration

      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
    networks:
      - mobile-banking-network

networks:
  mobile-banking-network:
    driver: bridge

volumes:
  postgres_data: